  name: 'Test'
  description: 'this is github action test'
  inputs:
    num:
      required: true
      default: "1"
  outputs:
    num_squared:
      description: 'Squrae'
      value: ${{ steps.get-square.outputs.num_squared }}
  runs:
    using: 'composite'
    steps:
     - name: Setup Python
       uses: actions/setup-python@v3.1.3
     - name: Install Dependencies
       run: pip install -r requirements.txt
       shell: bash
     - name: Pass Inputs to Shell
       run: |
          echo "INPUT_NUM=${{ input.num }}" >> $GITHUB_ENV
          shell: bash
     - name: Fetch the number's square
       id: get-square
       run: python src/get_num_square.py
       shell: bash
  
